[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cap_402_mxe = "Aaco6pyLJ6wAod2ivxS264xRcFyFZWdamy5VaqHQVC2d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/snjxlun1pUvKeI_EDZO8B9OVnE2575qH"
wallet = "~/.config/solana/devnet.json"

[test]
startup_wait = 120000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
